name: Build

on:
    push:
        branches: ["dev", "master"]
    pull_request:
        branches: ["dev", "master"]
    pull_request_target:
        types:
             - opened
        branches:
            - '*/*'

permissions:
    pull-requests: write
    contents: read

jobs:
    prettier_lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: yarn
        - run: yarn
        - run: yarn prettier
        - run: yarn lint

    unit_test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: yarn
        - run: yarn
        - run: yarn test --watchAll=false